# build stage
FROM golang:alpine AS build-env
RUN mkdir /src
ADD main.go /src
RUN cd /src && go build -o goapp

# final stage
FROM alpine
WORKDIR /app
COPY --from=build-env /src/goapp /app/
ENTRYPOINT ./goapp